### ISSUE TITLE
TODO for v1.1

### ISSUE THREAD

**Issue by stshryu** [stshryu/dndHelpers#1]
TODO:
- [ ] Remove Whitespaces and newlines at the end of Descriptions field
- [ ] Add import for items database
- [ ] Fix default selection on +1, -1 selection on item tracker
